'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.Commerce.ProductControls

    Partial Public Class SimpleProductControl

        '''<summary>
        '''ProductImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductImage As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''NameHyperLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameHyperLink As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''PriceLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PriceLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ShortDescriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShortDescriptionLiteral As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
