'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin.ContentManagement.EventModule

    Partial Public Class Events

        '''<summary>
        '''AddEventButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddEventButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''StatusMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusMessageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AddEventPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddEventPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''EventIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''TitleTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TitleTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvT As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceT As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''PermalinkTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PermalinkTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''EventDateTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventDateTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ceDateCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ceDateCalendar As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''TimeTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TimeTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''LocationTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LocationTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ImageIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ImageLocationLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageLocationLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ImageFileUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageFileUpload As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''DetailsTextArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailsTextArea As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''rfvD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvD As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceD As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''SubmitButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubmitButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CancelButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''EventsGridView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventsGridView As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''EventDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
