'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin.Commerce.Reports

    Partial Public Class DailyDiscountReport

        '''<summary>
        '''txbInitial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txbInitial As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txbFinal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txbFinal As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlReportType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlReportType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnGo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGo As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cxtInitial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cxtInitial As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''cxtFinal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cxtFinal As Global.AjaxControlToolkit.CalendarExtender

        '''<summary>
        '''btnDownloadCsv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDownloadCsv As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''litDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDay As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lvSalesDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lvSalesDays As Global.System.Web.UI.WebControls.ListView

        '''<summary>
        '''lvBranchDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lvBranchDays As Global.System.Web.UI.WebControls.ListView

        '''<summary>
        '''litYearlyCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litYearlyCost As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litYearlySales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litYearlySales As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litYearlyDiscounts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litYearlyDiscounts As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litYearlyProfit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litYearlyProfit As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
