'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCContentManagement

    Partial Public Class Links

        '''<summary>
        '''LinksRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinksRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''LinksDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinksDataSource As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''HeaderImageControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeaderImageControl1 As Global.CloudCar.CCControls.ContentManagement.PageModule.HeaderImageControl
    End Class
End Namespace
