'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCContentManagement

    Partial Public Class Unsuscribe

        '''<summary>
        '''txbUnsuscribe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txbUnsuscribe As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnUnsuscribe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUnsuscribe As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbmsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbmsg As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
