'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCContentManagement.VideosModule

    Partial Public Class Videos

        '''<summary>
        '''litFeaturedVideo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeaturedVideo As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litFeaturedTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeaturedTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litFeaturedDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litFeaturedDetails As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptVideos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptVideos As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
