'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin.Commerce

    Partial Public Class Colours

        '''<summary>
        '''hlBackToProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlBackToProduct As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hfColorID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfColorID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtColor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtColourCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtColourCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''tbwColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwColor As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvColor As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceColor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceColor As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''dgColors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgColors As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
