'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin.Commerce

    Partial Public Class ProductReviews

        '''<summary>
        '''phDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDetails As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''litName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litName As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEmail As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litAvatarURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAvatarURL As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litProduct As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litComment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litComment As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''gvProductReviews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvProductReviews As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
