'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin.Commerce

    Partial Public Class PromoCodes

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDetails As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''hfPromoCodeID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfPromoCodeID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSalesRep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSalesRep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDiscount As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ckbFixed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ckbFixed As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''rfvDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvDiscount As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceDiscount As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''ftbDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ftbDiscount As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''rfvSalesRep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSalesRep As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceSalesRep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceSalesRep As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''dgPromoCodes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPromoCodes As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
