'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin.ContentManagement.CallToActionModule

    Partial Public Class CallToAction

        '''<summary>
        '''NewButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NewButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''StatusMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusMessageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DetailsFormPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailsFormPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''CallToActionIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CallToActionIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''HeadingTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeadingTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''HeadingValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeadingValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''HeadingValidatorCallout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeadingValidatorCallout As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''ButtonTextTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonTextTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ButtonTextValidator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonTextValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''ButtonTextValidatorCallout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ButtonTextValidatorCallout As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''LinkUrlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkUrlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ImageUrlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImageUrlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DetailsTextArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailsTextArea As Global.System.Web.UI.HtmlControls.HtmlTextArea

        '''<summary>
        '''SaveButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CancelButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CallToActionRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CallToActionRepeater As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
