'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCBlogging

    Partial Public Class BlogEntries

        '''<summary>
        '''PageCanonicalMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageCanonicalMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litBlogDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBlogDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rbcRecentBlogs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbcRecentBlogs As Global.CloudCar.CCControls.Blogging.RecentBlogsControl

        '''<summary>
        '''tfcRecentTwitter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tfcRecentTwitter As Global.CloudCar.CCControls.Blogging.TwitterFeedControl

        '''<summary>
        '''rptBlogEntries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBlogEntries As Global.CloudCar.CCControls.DataPagerRepeater

        '''<summary>
        '''dpBlogEntries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dpBlogEntries As Global.System.Web.UI.WebControls.DataPager

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
