'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCBlogging

    Partial Public Class BlogPage

        '''<summary>
        '''PageKeywordsMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageKeywordsMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageDescriptionMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageDescriptionMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageCanonicalMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageCanonicalMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDatePosted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDatePosted As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''fblbControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fblbControl As Global.CloudCar.CCControls.Blogging.FBLikeButtonControl

        '''<summary>
        '''rbcRecentBlogs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbcRecentBlogs As Global.CloudCar.CCControls.Blogging.RecentBlogsControl

        '''<summary>
        '''hlAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAuthor As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''hlComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlComments As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''fcTwitterFacebook control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fcTwitterFacebook As Global.CloudCar.CCControls.Blogging.FollowUsControl

        '''<summary>
        '''fblbLikeBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fblbLikeBox As Global.CloudCar.CCControls.Blogging.FBLikeBoxControl

        '''<summary>
        '''tfcTwitterFeed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tfcTwitterFeed As Global.CloudCar.CCControls.Blogging.TwitterFeedControl

        '''<summary>
        '''litSubHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSubHeading As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''imgHeadingImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgHeadingImage As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''litBlogContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBlogContent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''imgAuthorPortrait control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAuthorPortrait As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''litAuthorDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAuthorDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''fbccComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fbccComments As Global.CloudCar.CCControls.Blogging.FBCommentsControl

        '''<summary>
        '''rptComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptComments As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''accAddComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents accAddComments As Global.CloudCar.CCControls.Blogging.AddCommentControl

        '''<summary>
        '''BreadCrumbLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BreadCrumbLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
