'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CloudCarDefault

    '''<summary>
    '''TempRotatorControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TempRotatorControl As Global.CloudCar.CCControls.ContentManagement.PageModule.JShowOffRotatorControl

    '''<summary>
    '''NivoRotatorControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NivoRotatorControl As Global.CloudCar.CCControls.ContentManagement.PageModule.NivoRotatorControl

    '''<summary>
    '''PageClearanceControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageClearanceControl As Global.CloudCar.CCControls.Commerce.ClearanceControl

    '''<summary>
    '''LatestControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LatestControl1 As Global.CloudCar.CCControls.Commerce.LatestControl

    '''<summary>
    '''PageQuickShipControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageQuickShipControl As Global.CloudCar.CCControls.Commerce.QuickShopControl

    '''<summary>
    '''PageSocialMediaControl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageSocialMediaControl As Global.CloudCar.CCControls.SocialMedia
End Class
