'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.ContentManagement.ProductControls

    Partial Public Class ProductControl

        '''<summary>
        '''pnlProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''imgProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgProduct As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''hlProductName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlProductName As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
