'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCMasterPages

    Partial Public Class Admin

        '''<summary>
        '''head control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''frmMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''tsmScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tsmScriptManager As Global.AjaxControlToolkit.ToolkitScriptManager

        '''<summary>
        '''imgLogoImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLogoImage As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''LoginView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LoginView1 As Global.System.Web.UI.WebControls.LoginView

        '''<summary>
        '''mdcMainMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdcMainMenu As Global.CloudCar.CCControls.ContentManagement.AdminMenuDisplayControl

        '''<summary>
        '''cphBeforeContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphBeforeContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''cphMainContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphMainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''TipMessageControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TipMessageControl1 As Global.CloudCar.CCControls.Admin.TipMessageControl

        '''<summary>
        '''AlertMessageControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AlertMessageControl1 As Global.CloudCar.CCControls.Admin.AlertMessageControl

        '''<summary>
        '''cphAfterContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphAfterContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''cphScripts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cphScripts As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
