'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCMasterPages

    Partial Public Class MainMaster

        '''<summary>
        '''Head1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''HeadContentPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HeadContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''frmMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''tsmScriptManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tsmScriptManager As Global.AjaxControlToolkit.ToolkitScriptManager

        '''<summary>
        '''UserAccountControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UserAccountControl1 As Global.CloudCar.CCControls.Admin.UserAccountControl

        '''<summary>
        '''MasterSearchControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MasterSearchControl As Global.CloudCar.CCControls.SearchControl

        '''<summary>
        '''MasterShoppingDetailsControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MasterShoppingDetailsControl As Global.CloudCar.CCControls.Commerce.ShoppingDetailsControl

        '''<summary>
        '''MenuDisplayControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuDisplayControl1 As Global.CloudCar.CCControls.ContentManagement.MenuDisplayControl

        '''<summary>
        '''MessagePlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MessagePlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''CategoriesControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoriesControl1 As Global.CloudCar.CCControls.Commerce.CategoriesControl

        '''<summary>
        '''QuickShopControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QuickShopControl1 As Global.CloudCar.CCControls.Commerce.QuickShopControl

        '''<summary>
        '''ClearanceControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ClearanceControl1 As Global.CloudCar.CCControls.Commerce.ClearanceControl

        '''<summary>
        '''TopSellersControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TopSellersControl1 As Global.CloudCar.CCControls.Commerce.TopSellersControl

        '''<summary>
        '''RotatorPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RotatorPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''FirstContentPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''SecondContentPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SecondContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''ThirdContentPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ThirdContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder

        '''<summary>
        '''SubscribeControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubscribeControl1 As Global.CloudCar.CCControls.SubscribeControl

        '''<summary>
        '''MenuDisplayControl2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuDisplayControl2 As Global.CloudCar.CCControls.ContentManagement.MenuDisplayControl

        '''<summary>
        '''MenuDisplayControl5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuDisplayControl5 As Global.CloudCar.CCControls.ContentManagement.MenuDisplayControl

        '''<summary>
        '''MenuDisplayControl4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuDisplayControl4 As Global.CloudCar.CCControls.ContentManagement.MenuDisplayControl

        '''<summary>
        '''MenuDisplayControl3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenuDisplayControl3 As Global.CloudCar.CCControls.ContentManagement.MenuDisplayControl

        '''<summary>
        '''RecentNewsControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RecentNewsControl As Global.CloudCar.CCControls.ContentManagement.NewsModule.RecentNewsControl

        '''<summary>
        '''UpcomingEventsControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpcomingEventsControl As Global.CloudCar.CCControls.ContentManagement.EventsModule.UpcomingEventsControl

        '''<summary>
        '''ScriptContentPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptContentPlaceHolder As Global.System.Web.UI.WebControls.ContentPlaceHolder
    End Class
End Namespace
