'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCCommerce

    Partial Public Class Details

        '''<summary>
        '''PageKeywordsMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageKeywordsMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageDescriptionMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageDescriptionMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageCanonicalMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageCanonicalMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''StatusMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusMessageLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageBreadCrumbControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageBreadCrumbControl As Global.CloudCar.CCControls.ContentManagement.PageModule.BreadCrumbControl

        '''<summary>
        '''MoreImagesHyperLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MoreImagesHyperLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''PintrestAnchor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PintrestAnchor As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''DefaultImageHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DefaultImageHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''DefaultSmallImageHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DefaultSmallImageHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''DefaultImageDescriptionHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DefaultImageDescriptionHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ImagesThumbnailRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImagesThumbnailRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''ProductTitleLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductTitleLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ProductBrandLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductBrandLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ProductCodeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductCodeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''AvailabilityLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AvailabilityLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''SoldOutLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SoldOutLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ReviewsLinkLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReviewsLinkLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ProductListPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductListPrice As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ProductPriceLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductPriceLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ProductSizeDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductSizeDropDownList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ProductColorDropDownList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductColorDropDownList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ProductQuantityTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductQuantityTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvQuantity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''tbwQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwQuantity As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''vceQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceQuantity As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''AddToCartButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddToCartButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''AverageProductRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AverageProductRating As Global.AjaxControlToolkit.Rating

        '''<summary>
        '''ProductDescriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductDescriptionLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ReviewsRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReviewsRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''prcReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents prcReview As Global.CloudCar.CCControls.Commerce.AddProductReviewControl

        '''<summary>
        '''DetailsRecomendedProductControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DetailsRecomendedProductControl As Global.CloudCar.CCControls.Commerce.ProductControls.RecomendedProductControl

        '''<summary>
        '''ShoppingProgressControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingProgressControl1 As Global.CloudCar.CCControls.Commerce.ShoppingProgressControl

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
