'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCCommerce

    Partial Public Class ProductsPage

        '''<summary>
        '''PageKeywordsMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageKeywordsMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageDescriptionMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageDescriptionMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageCanonicalMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageCanonicalMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageBreadCrumbControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageBreadCrumbControl As Global.CloudCar.CCControls.ContentManagement.PageModule.BreadCrumbControl

        '''<summary>
        '''PageHeadingLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageHeadingLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''RcNivoRotator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RcNivoRotator As Global.CloudCar.CCControls.ContentManagement.PageModule.NivoRotatorControl

        '''<summary>
        '''ShoppingProgressControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingProgressControl1 As Global.CloudCar.CCControls.Commerce.ShoppingProgressControl

        '''<summary>
        '''lblDummy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDummy As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''PriceRangeDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PriceRangeDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''BrandDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BrandDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ColorDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ColorDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ProductRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''ProductCountLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProductCountLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''mpeConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mpeConfirm As Global.AjaxControlToolkit.ModalPopupExtender

        '''<summary>
        '''lblDisplaySelectedProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplaySelectedProducts As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''udpInnerUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents udpInnerUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''btnContinueShopping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnContinueShopping As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''hlGoToCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlGoToCart As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''PageContentLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageContentLiteral As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
