'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCCommerce

    Partial Public Class ShoppingCartPage

        '''<summary>
        '''ShoppingProgressControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingProgressControl1 As Global.CloudCar.CCControls.Commerce.ShoppingProgressControl

        '''<summary>
        '''ShoppingCartUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingCartUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''CartWeightLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CartWeightLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''StatusMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusMessageLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ShoppingCartPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingCartPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ShoppingCartItemsRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingCartItemsRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''TotalHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''UpdateCartButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdateCartButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''TotalLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalLiteral As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CheckStepOneImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckStepOneImage As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AddressTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddressTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CityTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CityTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ProvinceDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ProvinceDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CountryDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CountryDropDown As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PostalCodeTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostalCodeTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShippingOptionsButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingOptionsButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CheckStepTwoImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckStepTwoImage As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''SelectedRateHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SelectedRateHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ShippingRateLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingRateLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ShippingOptionsRadioList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingOptionsRadioList As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''ShippingChargesLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingChargesLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''PromoCodeTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PromoCodeTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PromoDiscountLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PromoDiscountLiteral As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CheckoutButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckoutButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ContinueShoppingButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContinueShoppingButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tbwAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwAddress As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceAddress As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''tbwCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwCity As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceCity As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCountry As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceCountry As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvProvince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvProvince As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceProvince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceProvince As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''tbwPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwPostalCode As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPostalCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vcePostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vcePostalCode As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvSOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSOptions As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceSOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceSOptions As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''tbwPromoCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwPromoCode As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''upProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upProgress As Global.System.Web.UI.UpdateProgress

        '''<summary>
        '''HelpButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HelpButton1 As Global.CloudCar.CCControls.HelpButtonControl

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
