'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCCommerce

    Partial Public Class ThankYou

        '''<summary>
        '''FirstNameLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FirstNameLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''OrderIdLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrderIdLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ShoppingProgressControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShoppingProgressControl1 As Global.CloudCar.CCControls.Commerce.ShoppingProgressControl

        '''<summary>
        '''CustomerInformationLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CustomerInformationLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hlSupportEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlSupportEmail As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''OrderItemsLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrderItemsLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''OrderItemsRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OrderItemsRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''SubTotalLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTotalLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ShippingChargeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingChargeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''DiscountLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DiscountLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''TaxRateLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TaxRateLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''TaxChargesLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TaxChargesLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''TotalLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''BillingMethodLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BillingMethodLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''AuthorizationCodeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AuthorizationCodeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''BillingAmountLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BillingAmountLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''BillingAddressLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BillingAddressLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ShippingAddressLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingAddressLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ShippingDetailsLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShippingDetailsLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
