'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCContentManagement

    Partial Public Class CMSDetails

        '''<summary>
        '''imgMainProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgMainProduct As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''litProductTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litProductTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litProductDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litProductDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litBreadCrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBreadCrumb As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hlMoreImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlMoreImages As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''rptReviews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptReviews As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''prcReview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents prcReview As Global.CloudCar.CCControls.Commerce.AddProductReviewControl
    End Class
End Namespace
