'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCCommerce.Email

    Partial Public Class DistributorOrderInvoice

        '''<summary>
        '''litOrderID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litOrderID As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hlDistributorOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlDistributorOrders As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''dgOrderItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgOrderItems As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''litCustomerInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCustomerInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBillingAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillingAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblShippingAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShippingAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblShipCompany control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShipCompany As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblShipService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShipService As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeight As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblShipCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShipCharge As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBillMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillMethod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBillingAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillingAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litOrderItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litOrderItems As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litSubTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSubTotal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDiscount As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litShipCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litShipCharge As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTaxRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTaxRate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTaxAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTaxAmount As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotal As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
