Imports CloudCar.CCFramework.Core

Namespace CCAuthentication
    Partial Public Class ResetPassword
        Inherits Page

        Protected Sub PageLoad(ByVal Sender As Object, ByVal E As EventArgs) Handles Me.Load

        End Sub

        Private Sub SubmitButtonCommand(ByVal Sender As Object, ByVal E As CommandEventArgs) Handles btnSubmit.Command
            Dim CurrentUserName As String = txtUserName.Text
            Dim CurrentEmail As String = txtEmail.Text

            Dim CurrentUser As MembershipUser = Membership.GetUser(CurrentUserName)

            If CurrentUser.Email.ToLower = CurrentEmail.ToLower Then
                phQuestion.Visible = True
                phUser.Visible = False

                btnResetPassword.Attributes.Add("UserName", CurrentUser.UserName)

                litUser.Text = CurrentUser.UserName
                litQuestion.Text = String.Format("{0}?", CurrentUser.PasswordQuestion)
            End If
        End Sub

        Protected Sub ResetPasswordButtonCommand(ByVal Sender As Object, ByVal E As CommandEventArgs) Handles btnResetPassword.Command
            Dim CurrentUserName As String = btnResetPassword.Attributes("UserName")
            Dim CurrentPassword As String = ""
            Dim CurrentAnswer As String = txtPwdAnswer.Text

            If RegisteredUserController.ResetUserPassword(CurrentUserName, CurrentPassword, CurrentAnswer) Then
                lblStatus.Text = String.Format("{0}'s password has been successfully reset. You will be notified, by email, of your new password.", CurrentUserName)  'to ( <b>" & password & "</b> ).
                lblStatus.Visible = True

                phQuestion.Visible = False
                phUser.Visible = False

                If Settings.SendNoticeEmails Then
                    'TODO add a link to change your password form.
                    Dim ResetMessage As New StringBuilder

                    ResetMessage.Append(String.Format("This is an automated message from {0} to inform you that your password has been reset. <br /><br />", Settings.CompanyName))
                    ResetMessage.Append(String.Format("You new password is  <b>{0}</b><br /><br />", CurrentPassword))
                    ResetMessage.Append("Go to the Change Password page to change this autogenerated password. Thank you for visiting our site.")

                    SendEmails.Send(New Net.Mail.MailAddress(Membership.GetUser(CurrentUserName).Email), String.Format("{0} - Your password has been reset.", Settings.CompanyName), ResetMessage.ToString)
                End If
            Else
                lblStatus.Text = String.Format("There was an error reseting your password. {0}", CurrentPassword)
                lblStatus.Visible = True
            End If
        End Sub

    End Class
End Namespace