'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.Commerce

    Partial Public Class PaybackTotalControl

        '''<summary>
        '''litCostOfWebsite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCostOfWebsite As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litCostOfGoodsSold control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCostOfGoodsSold As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTotalSales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalSales As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTotalProfitFromSales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotalProfitFromSales As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litAmountRemaining control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAmountRemaining As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
