'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.Commerce

    Partial Public Class ShoppingDetailsControl

        '''<summary>
        '''litItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litItems As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''CartEmptyLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CartEmptyLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''CartMiniItemsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CartMiniItemsLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''MiniCartItemsRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MiniCartItemsRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''CartMiniTotalLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CartMiniTotalLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''TotalLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''CartMiniButtonsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CartMiniButtonsLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
