'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace CCAuthentication
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AuthenticationResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CloudCar.AuthenticationResources", GetType(AuthenticationResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill out the below form to change your current password to a new one..
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordHelpMessage() As String
            Get
                Return ResourceManager.GetString("ChangePasswordHelpMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill out the below form to change your password..
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordMessage1() As String
            Get
                Return ResourceManager.GetString("ChangePasswordMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Be sure to remember your new passord when logging in next time..
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordMessage2() As String
            Get
                Return ResourceManager.GetString("ChangePasswordMessage2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Success!.
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordSuccessHeading() As String
            Get
                Return ResourceManager.GetString("ChangePasswordSuccessHeading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your password has been successfully changed..
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordSuccessMessage() As String
            Get
                Return ResourceManager.GetString("ChangePasswordSuccessMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Friend Shared ReadOnly Property ChangePasswordTitle() As String
            Get
                Return ResourceManager.GetString("ChangePasswordTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Confirm New Password.
        '''</summary>
        Friend Shared ReadOnly Property ConfirmNewPassword() As String
            Get
                Return ResourceManager.GetString("ConfirmNewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;b&gt;Ooops!&lt;/b&gt; There was an error trying to log you in! Please make sure your username and password are correct..
        '''</summary>
        Friend Shared ReadOnly Property LoginFailedMessage() As String
            Get
                Return ResourceManager.GetString("LoginFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill out your credentials and login to access your account information..
        '''</summary>
        Friend Shared ReadOnly Property LoginHelpMessage() As String
            Get
                Return ResourceManager.GetString("LoginHelpMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thank you for coming back! Please login to continue..
        '''</summary>
        Friend Shared ReadOnly Property LoginMessage1() As String
            Get
                Return ResourceManager.GetString("LoginMessage1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have been successfully logged in..
        '''</summary>
        Friend Shared ReadOnly Property LoginSuccessMessage() As String
            Get
                Return ResourceManager.GetString("LoginSuccessMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login to your account.
        '''</summary>
        Friend Shared ReadOnly Property LoginTitle() As String
            Get
                Return ResourceManager.GetString("LoginTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Password.
        '''</summary>
        Friend Shared ReadOnly Property NewPassword() As String
            Get
                Return ResourceManager.GetString("NewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Old Password.
        '''</summary>
        Friend Shared ReadOnly Property OldPassword() As String
            Get
                Return ResourceManager.GetString("OldPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
