'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.ContentManagement

    Partial Public Class RecentVideoControl

        '''<summary>
        '''VideoPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VideoPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''FeaturedVideoLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FeaturedVideoLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''VideoTitleLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VideoTitleLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''VideoDescriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VideoDescriptionLiteral As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
