'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCContentManagement.FormModule

    Partial Public Class FormDisplay

        '''<summary>
        '''FormIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''FormNameLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormNameLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''FormDetailsLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormDetailsLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''FormFieldsPlaceHolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormFieldsPlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''FormSubmitButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FormSubmitButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
