USE [master]
GO

/****** Object:  Database [CloudCarDemoDb]    Script Date: 2018-09-17 10:49:50 PM ******/
CREATE DATABASE [CloudCarDemoDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMECommerceTemplateDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\CloudCarDemoDb_data.mdf' , SIZE = 90112KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SMECommerceTemplateDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\CloudCarDemoDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CloudCarDemoDb] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CloudCarDemoDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CloudCarDemoDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CloudCarDemoDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CloudCarDemoDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CloudCarDemoDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CloudCarDemoDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CloudCarDemoDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CloudCarDemoDb] SET  MULTI_USER 
GO

ALTER DATABASE [CloudCarDemoDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CloudCarDemoDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CloudCarDemoDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CloudCarDemoDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CloudCarDemoDb] SET  READ_WRITE 
GO

