'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Namespace CCControls.ContentManagement.EventsModule

    Partial Public Class EventsCalendar

        '''<summary>
        '''EventsCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventsCalendar As Global.System.Web.UI.WebControls.Calendar
    End Class
End Namespace