'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.Blogging

    Partial Public Class AddCommentControl

        '''<summary>
        '''BlogIdHiddenField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BlogIdHiddenField As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''NameTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NameTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''EmailTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EmailTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''UrlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UrlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CommentTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CommentTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CreateCommentButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CreateCommentButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
