'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.Blogging

    Partial Public Class LatestBlogControl

        '''<summary>
        '''hlBlogLinkHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlBlogLinkHeading As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''litHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litHeading As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDetails As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hlBlogLinkBottom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlBlogLinkBottom As Global.System.Web.UI.HtmlControls.HtmlAnchor
    End Class
End Namespace
