'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCCommerce.Mobile

    Partial Public Class MobileCheckout

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ifVBVContents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ifVBVContents As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litOrderItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litOrderItems As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litSubTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSubTotal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litShipCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litShipCharge As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDiscount As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTaxRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTaxRate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTaxAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTaxAmount As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTotal As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''litSAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSAddress As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ckbSameAsShipping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ckbSameAsShipping As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''tblBillingAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblBillingAddress As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''txtBAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtBCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlBCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBCountry As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlBProvince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBProvince As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtBPC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBPC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''tbwBAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwBAddress As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvBAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvBAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceBAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceBAddress As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvBCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvBCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceBCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceBCity As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvBPC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvBPC As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceBPC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceBPC As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvBCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvBCountry As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceBCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceBCountry As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvBProvince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvBProvince As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceBProvince control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceBProvince As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''ddlCardType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCardType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCCNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCCNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCCCVD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCCCVD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCCName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCCName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlExpMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlExpMonth As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlExpYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlExpYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rfvEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceEmail As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvPN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvPN As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vcePN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vcePN As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''tbwCCNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwCCNumber As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvCCNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCCNumber As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceCCNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceCCNumber As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvCCName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCCName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceCCName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceCCName As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''tbwCCCVD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbwCCCVD As Global.AjaxControlToolkit.TextBoxWatermarkExtender

        '''<summary>
        '''rfvCCCVD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvCCCVD As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceCCCVD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceCCCVD As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvExpMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvExpMonth As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceExpMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceExpMonth As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rfvExpYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvExpYear As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''vceExpYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vceExpYear As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''btnPurchase control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPurchase As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
