Namespace CCFramework.Commerce.Shipping.Purolator

    Public Enum PurolatorServiceType
        PurolatorExpress9AM = 1
        PurolatorExpress1030AM = 2
        PurolatorExpress = 3
        PurolatorExpressEvening = 4
        PurolatorExpressEnvelope9AM = 5
        PurolatorExpressEnvelope1030AM = 6
        PurolatorExpressEnvelope = 7
        PurolatorExpressEnvelopeEvening = 8
        PurolatorExpressPack9AM = 9
        PurolatorExpressPack1030AM = 10
        PurolatorExpressPack = 11
        PurolatorExpressPackEvening = 12
        PurolatorExpressBox9AM = 13
        PurolatorExpressBox1030AM = 14
        PurolatorExpressBox = 15
        PurolatorExpressBoxEvening = 16
        PurolatorGround = 17
        PurolatorGround9AM = 18
        PurolatorGround1030AM = 19
        PurolatorGroundEvening = 20
        PurolatorExpressUS9AM = 21
        PurolatorExpressUS1030AM = 22
        PurolatorExpressUS = 23
        PurolatorExpressUS12 = 24
        PurolatorExpressUSEnvelope9AM = 25
        PurolatorExpressUSEnvelope1030AM = 26
        PurolatorExpressEnvelopeUS = 27
        PurolatorExpressUSEnvelope12 = 28
        PurolatorExpressUSPack9AM = 29
        PurolatorExpressUSPack1030AM = 30
        PurolatorExpressPackUS = 31
        PurolatorExpressUSPack12 = 32
        PurolatorExpressUSBox9AM = 33
        PurolatorExpressUSBox1030AM = 34
        PurolatorExpressBoxUS = 35
        PurolatorExpressUSBox12 = 36
        PurolatorGroundUS = 37
        PurolatorExpressInternational9AM = 38
        PurolatorExpressInternational1030AM = 39
        PurolatorExpressInternational = 40
        PurolatorExpressInternational12 = 41
        PurolatorExpressInternationalEnvelope9AM = 42
        PurolatorExpressInternationalEnvelope1030AM = 43
        PurolatorExpressEnvelopeInternational = 44
        PurolatorExpressInternationalEnvelope12 = 45
        PurolatorExpressInternationalPack9AM = 46
        PurolatorExpressInternationalPack1030AM = 47
        PurolatorExpressPackInternational = 48
        PurolatorExpressInternationalPack12 = 49
        PurolatorExpressInternationalBox9AM = 50
        PurolatorExpressInternationalBox1030AM = 51
        PurolatorExpressBoxInternational = 52
        PurolatorExpressInternationalBox12 = 53
        PurolatorGroundDistribution = 54
    End Enum

End Namespace