'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin

    Partial Public Class DatabaseConsole

        '''<summary>
        '''StatusLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''QueryTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents QueryTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubmitQueryButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubmitQueryButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''CommandTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CommandTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubmitCommandButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubmitCommandButton As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
