'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin

    Partial Public Class Dashboard

        '''<summary>
        '''GuestUsersLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GuestUsersLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''RegisteredUsersLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegisteredUsersLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''TotalUsersLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalUsersLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''RestartApplicationButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RestartApplicationButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''phSales control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSales As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''InventoryRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InventoryRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''TopSellersRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TopSellersRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''ptcTotals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ptcTotals As Global.CloudCar.CCControls.Commerce.PaybackTotalControl

        '''<summary>
        '''litNewLeads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litNewLeads As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''phStoreControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phStoreControls As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''litUnshippedOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litUnshippedOrders As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
