'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCAdmin

    Partial Public Class Maintenance

        '''<summary>
        '''StatusMessageLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StatusMessageLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TotalShoppingCartsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalShoppingCartsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RegisteredShoppingCartsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RegisteredShoppingCartsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UnregisteredShoppingCartsLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnregisteredShoppingCartsLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DeleteUnregisteredShoppingCartsButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeleteUnregisteredShoppingCartsButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''TotalImagesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalImagesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UsedImagesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UsedImagesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UnusedImagesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnusedImagesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''WaistedBytesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WaistedBytesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DeleteUnusedImagesButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeleteUnusedImagesButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UnusedImagesRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnusedImagesRepeater As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''TotalAddressesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TotalAddressesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LinkedAddressesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkedAddressesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UnusedAddressesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnusedAddressesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DeleteUnusedAddressesButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DeleteUnusedAddressesButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''UnusedAddressRepeater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UnusedAddressRepeater As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
