'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCContentManagement.NewsModule

    Partial Public Class NewsDetails

        '''<summary>
        '''PageKeywordsMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageKeywordsMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageDescriptionMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageDescriptionMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''PageCanonicalMeta control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageCanonicalMeta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''TitleLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TitleLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''SubTitleLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTitleLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ThumbnailImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ThumbnailImage As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''ContentLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContentLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''EventBreadCrumbControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EventBreadCrumbControl As Global.CloudCar.CCControls.ContentManagement.PageModule.BreadCrumbControl

        '''<summary>
        '''PageScriptManagementControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageScriptManagementControl As Global.CloudCar.CCControls.ContentManagement.CloudCarScriptManagementControl
    End Class
End Namespace
