'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace CCControls.Commerce.ClientControls

    Partial Public Class BoxCalculatorControl

        '''<summary>
        '''smpProxy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents smpProxy As Global.System.Web.UI.ScriptManagerProxy

        '''<summary>
        '''lblDummy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDummy As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''rptBoxCalc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBoxCalc As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''btnBCSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBCSubmit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''upBoxCalc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upBoxCalc As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''mpeConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mpeConfirm As Global.AjaxControlToolkit.ModalPopupExtender

        '''<summary>
        '''lblDisplaySelectedProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplaySelectedProducts As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''udpInnerUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents udpInnerUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''rptProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptProducts As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''btnContinueShopping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnContinueShopping As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''btnAddToCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddToCart As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
